### ISSUE TITLE
[bug] sometimes breakpoint cannot make the line number become red

### ISSUE THREAD

**Issue by Freed-Wu** [cgdb/cgdb#317] opened 2022-04-21 03:05 UTC
take <https://github.com/mirror/x264> as an example:

```
$ git clone --depth=1 https://github.com/mirror/x264
$ cd x264
$ ./configure --enable-debug
$ make
$ vi .gdbinit
$ cat .gdbinit
start
b encoder/encoder.c:3337
# you should provide a yuv file as input
$ cgdb -- --args ./x264 -o a.264 /mnt/yuv/paris_cif_352x288.yuv
# in cgdb, type `continue`, will break in encoder/encoder.c:3337
```

![Screenshot from 2022-04-21 11-03-31](https://user-images.githubusercontent.com/32936898/164363465-77479230-058c-4c14-8371-af3c22deb466.png)

break line before 3337 will make line number become red:

![Screenshot from 2022-04-21 11-03-46](https://user-images.githubusercontent.com/32936898/164363515-895eba46-1f95-4d6f-9943-6967f2767c6d.png)

however, break line after 3337 will not make line number become red, although the breakpoint exist.

Thanks.

**Comment by brasko** [comment] 2024-05-10 01:34
@Freed-Wu Thanks for pointing this out. It looks like cgdb is having a problem when the breakpoint matches multiple addresses,
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   0x000000000002aa56 in x264_8_encoder_encode
                                                   at encoder/encoder.c:3333
2       breakpoint     keep y   <MULTIPLE>
2.1                         y   0x000000000002aa6e in x264_8_encoder_encode
                                                   at encoder/encoder.c:3337
2.2                         y   0x000000000003ef0f in x264_10_encoder_encode
                                                   at encoder/encoder.c:3337

I'll do a little research on this.

**Comment by brasko** [comment] 2024-05-10 01:40
I was able to reproduce this with the following files,
$ cat main.h 
int fn(int a, int b)
{
    int result;
    result = a + b;
    return result;
}

$ cat main.c 
#define fn SUM1
#include "main.h"
#undef fn
#define fn SUM2
#include "main.h"

int main()
{
    int total;

    total = SUM1(1, 3);

    total += SUM2(2, 4);

    return total;
}

Then compiling the main, gcc -g -o main main.c, then debugging with cgdb and attempting to set a breakpoint in header function.

**Comment by brasko** [comment] 2024-05-10 01:42
A more standard reproducer is as follows,
$ cat main.cpp 
template <typename T>
struct S {
    int sum(int a, int b)
    {
        int total;
        total = a + b;
        return total;
    }
};

int main()
{
    int total;
    S<int> one;
    S<float> two;

    total = one.sum(1, 3);
    total += two.sum(2, 4);
    return total;
}

Then attempt to set a breakpoint in the template function.

**Comment by brasko** [comment] 2024-05-10 02:54
I should have a fix for this soon. gdb changed it's breakpoint syntax quite a while ago. I've got it working locally but i need to test it a little further.

**Comment by brasko** [comment] 2024-05-11 01:52
@Freed-Wu This has been fixed. Thanks again for the report.

**Closed by brasko** 2024-05-11 01:52 UTC
