### ISSUE TITLE
race condition during search

### ISSUE THREAD

**Issue by leissa** [cgdb/cgdb#200] opened 2019-03-10 18:34 UTC
Steps to reproduce:

1. fire up `cgdb --args my_prg --my_args`
2. run `r`
3. open a file:
    * `o`
    * select some file and press `enter`
4. Immediately after pressing `enter` type __as fast as you can__ `/asdf` to search for some phrase `asdf` in the source file. CGDB will hang; presumably because of some race condition.

Occurs almost always on my system. Waiting a second or so after having opened the file and *then* search in the file works around the problem.

**Comment by brasko** [comment] 2019-08-03 19:14
I have a feeling this issue was already fixed in master,
  * Fix issue #161 - CGDB would lock up when doing a regex search from
    the status bar if the file was just opened from the file dialog and
    the search did not match any text in the file. Now the search fails
    to match text as expected.

Can you tell me if you can still reproduce this issue when compiling from master?

**Comment by brasko** [comment] 2021-03-14 16:46
I can't reproduce this, if anyone else runs into this issue, please let me know.

**Closed by brasko** 2021-03-14 16:46 UTC
