### ISSUE TITLE
Time for v0.7.2 or v0.8.0?

### ISSUE THREAD

**Issue by ericcurtin** [cgdb/cgdb#294] opened 2021-11-16 19:42 UTC
Thanks so much for your work on this. I notice the master version of cgdb seems quite superior to v0.7.1 and in particular it handles colours and escape sequences much better. Time for a new release? There hasn't been a release in over two years, even though there has been much progress!

**Comment by brasko** [comment] 2021-11-18 02:22
Thanks for appreciating the work.
Yes, a release will be made relatively soon.
I have noticed that after all of the major changes, I keep getting bug reports, about one a week.
Once I see this slow down I'll proceed with a release.
I'm closing this as a duplicate of #253.

**Closed by brasko** 2021-11-18 02:22 UTC
