### ISSUE TITLE
'layout' command breaks cgdb

### ISSUE THREAD

**Issue by fabioperez** [cgdb/cgdb#57] opened 2015-01-08 17:01 UTC
When I try to use the command `layout <some layout>`, the cgdb behaves oddly. I could not even quit cgdb.

![cgdb](https://cloud.githubusercontent.com/assets/294960/5666498/202f91dc-9747-11e4-8b29-976189ad921c.png)

**Comment by reisgabrieljoao** [comment] 2015-03-25 11:51
I'm having the same issue with CGDB 0.6.5 on Ubuntu 12.04 however, I'm not sure if different layout are supposed to be supported as they are TUI specific commands.

**Comment by crowell** [comment] 2015-09-30 05:08
@fabioperez this is due to the scroller being unable to parse non-ascii stuff.

**Comment by scottlu** [comment] 2016-05-05 23:56
This puts gdb into TUI mode which CGDB isn't compatible with. This is a duplicate of #73.

**Comment by brasko** [comment] 2016-08-12 10:52
Thanks to Michael Sartain there is a black list of commands now in cgdb that the user is no longer allowed to run. This prevents the behavior you found. These changes are in master.

**Closed by brasko** 2016-08-12 10:52 UTC
