### ISSUE TITLE
cgdb crashes while resizing window

### ISSUE THREAD

**Issue by vlachoudis** [cgdb/cgdb#303] opened 2022-01-18 16:51 UTC
Recently I moved to a tile window manager **i3** which constantly resizes the window so as to use the whole screen.
While running a big multithreaded program through **cgdb**, when I open a new window the cgdb window is resized and **cgdb** crashes with a seg-fault.
Traceback:
```
(gdb) bt
#0  0x00005637d6f91ffb in on_text (
    bytes=0x7efda3748017 "GNU gdb (Ubuntu 11.1-0ubuntu2) 11.1\033[m\r\nCopyright (C) 2021 Free So
ftware Foundation, Inc.\r\nLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gp
l.html>\r\nThis is free software: you are"..., len=7710538, user=0x5637d8ea6c30) at state.c:279
#1  0x00005637d6f8ef57 in vterm_input_write (vt=0x5637d9a23220,
    bytes=0x7efda3748010 "\033[35;1mGNU gdb (Ubuntu 11.1-0ubuntu2) 11.1\033[m\r\nCopyright (C) 20
21 Free Software Foundation, Inc.\r\nLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/l
icenses/gpl.html>\r\nThis is free software: "..., len=7710545) at parser.c:360
#2  0x00005637d6f72ce1 in VTerminal::write (len=<optimized out>, data=<optimized out>,
    this=0x5637d8ef73a0) at vterminal.cpp:214
#3  vterminal_write (terminal=0x5637d8ef73a0, data=<optimized out>, len=<optimized out>)
    at vterminal.cpp:509
#4  0x00005637d6f71ac6 in scr_move (scr=<optimized out>, win=<optimized out>)
    at scroller.cpp:321
#5  0x00005637d6f6ea0d in if_layout () at interface.cpp:569
#6  0x00005637d6f6ec6e in if_resize_term () at interface.cpp:598
#7  0x00005637d6f672a6 in cgdb_resize_term (fd=11) at cgdb.cpp:733
#8  main_loop () at cgdb.cpp:810
#9  main (argc=<optimized out>, argv=<optimized out>) at cgdb.cpp:1166
```

For some reason the **len** argument has a value of **7710538**
which makes a seg fault trying to allocate int he line below
`uint32_t codepoints[len];`

**len** is the length of the text of `gdb_scroller`
My impression if the gdb_scroller collects too much output text, resizing the window leads to the crash

If you compile the following code and run it through the cgdb
```
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

int main(int ac, char* av[])
{
        for (int i=0; i<atoi(av[1]); i++)
                printf("The quick brown fox jumps over the lazy dogs tail %d\n",i);
        assert(atoi(av[1])==10);
        return 0;
} // main
```

`$ cgdb --args a.out 100000000`
after a certain output size, resizing the window leads to a crash

**Comment by vlachoudis** [comment] 2022-01-20 07:59
With the following change:
```
diff --git a/lib/vterm/state.c b/lib/vterm/state.c
index d5f3a30..28ab6d4 100644
--- a/lib/vterm/state.c
+++ b/lib/vterm/state.c
@@ -276,7 +276,8 @@ static int on_text(const char bytes[], size_t len, void *user)
   VTermPos oldpos = state->pos;
 
   // We'll have at most len codepoints
-  uint32_t codepoints[len];
+  int cplen = len<100000?len:100000;
+  uint32_t codepoints[cplen];
   int npoints = 0;
   size_t eaten = 0;
 
@@ -287,7 +288,7 @@ static int on_text(const char bytes[], size_t len, void *user)
                              &state->encoding[state->gr_set];
 
   (*encoding->enc->decode)(encoding->enc, encoding->data,
-      codepoints, &npoints, state->gsingle_set ? 1 : len,
+      codepoints, &npoints, state->gsingle_set ? 1 : cplen,
       bytes, &eaten, len); 
```
setting an upper limit of codepoints, now it doesn't crash.
However I believe that is better to trim the **text** up to a certain limit, since
now when it grows a lot after a resize it takes some time to refresh

**Comment by brasko** [comment] 2022-01-21 01:59
Sorry for the late response. I've been sick.
This is a bad bug indeed. No one wants a crash after a long debug session.

Let me ask you a question. How much of the gdb window is valuable over time?
We already have a new option that limits the scrollback buffer size,
    - The scrollback buffer size is configurable with a new option,
      scrollbackbuffersize (sbbs) and is defaulted to 10000.
I wonder if that's related here. Or if we need a new option.
It does seem pointless to attempt to send all that text back through the terminal emulator for a resize.....

**Comment by auouymous** [comment] 2022-01-21 03:17
I don't see why it would be sending the entire sbbs buffer unless that option is bytes and it doesn't know how many lines are in it or where they begin. Otherwise, just get the new terminal height, recalculate output section height and output only the most recent lines that would fill the output section. It already resets scrolling to bottom when resized, so that isn't an issue. And it could account for lines that wrap, and reduce the number sent, but that shouldn't matter for most cases.

**Comment by vlachoudis** [comment] 2022-01-21 07:34
@brasko your question has no easy answer. For me scrolling back a few 1000 of lines and I will be lost, unless if I have some kind of search capability. So your default of 10k lines is more than enough for me.

I would tend to agree with @auouymous you need to redisplay only the last page, so no need to scan the entire buffer. Unless if you are afraid that some format encoding started before the last page and it is still active. So maybe you can scan a few pages back (or set it as a user option, a bit overkill for me)

**Comment by brasko** [comment] 2022-01-23 01:43
@vlachoudis CGDB does have a searchable gdb window. That might not have been known.
In the GDB window, hit Page Up, and then start moving around or searching with ? and /.

**Comment by brasko** [comment] 2022-01-23 01:51
@vlachoudis Thanks for the reproducer, I just verified it crashes for me as well.
It's really a shame I just released 0.8.0. I might have to release 0.8.1 immediately.

**Comment by brasko** [comment] 2022-01-23 02:21
I've asked the upstream author if he agrees that it is a bug in vterm and if he is willing to fix it. I'll follow up soon hopefully.

**Comment by vlachoudis** [comment] 2022-01-23 12:15
@brasko thanks for the tip. I need to read the manual :)

**Comment by brasko** [comment] 2022-01-23 16:12
The vterm author wrote to me: "Sounds like a bug, yes. I should look into it a bit"
Lets see how that plays out.

**Comment by brasko** [comment] 2022-01-28 02:33
The upstream author is busy and suggested I try to provide a patch. O boy.

**Comment by brasko** [comment] 2022-01-28 03:33
I have a solution that works by resizing the vterm instance on the resize of the terminal. It doesn't crash and it's instantly fast. The problem is, if you resize the gdb window larger, the text doesn't reflow, so the right hand side is empty. If you resize it smaller, you lose the text that was in the columns you shrunk. What this solution be useful to you?

**Comment by auouymous** [comment] 2022-01-28 04:33
You lose the text in both cases when it crashes, so this is better than nothing right now. Bash sometimes reflows text when resizing and other times it leaves empty space or wraps parts of the text. I don't think anyone would have a problem with the empty space, but I can see another issue being opened about cutting off the text when resizing smaller. That problem could be fixed later if a solution is found, and if anyone actually resizes smaller while debugging, but it is more likely you resize larger to see more text.

**Comment by vlachoudis** [comment] 2022-01-28 07:27
@brasko that's fine as long as **Ctrl-l** will work to redraw the screen.
I don't know if it is possible you can set a timer event that few (1-2) sec after a resize (whewhen it redraws the screen

**Comment by vlachoudis** [comment] 2022-01-28 07:29
@brasko that's fine as long as **Ctrl-l** will work to redraw the screen.
I don't know if it is possible to avoid multiple redraws during the resize, you can set a timer event that after a few (1-2) sec or on idle (when resize stopped) to redraws the screen

**Comment by brasko** [comment] 2022-01-30 14:03
I've committed the fix that fixes the crash. It is also efficient by using vterm resize. However the text may not appear as nicely as it did before as vterm doesn't support reflow yet. This is a feature request which may or may not ever get done.

**Closed by brasko** 2022-01-30 14:03 UTC

**Comment by vlachoudis** [comment] 2022-01-30 18:26
Many thanks
