### ISSUE TITLE
[regression in master] Debugger always stops with: --Type <RET> for more, q to quit, c to continue without paging--

### ISSUE THREAD

**Issue by yurivict** [cgdb/cgdb#297] opened 2021-11-24 22:01 UTC
```0.7.1``` didn't do this, and the current master 61e3606 does.

This happens both in a regular invocation and when invoked as attached debugger:
```cgdb -p {pid}```

gdb-11.1
FreeBSD 13

**Comment by dflogeras** [comment] 2021-12-04 14:17
You can make this slightly less annoying by adding the option to your .gdbinit file

set pagination off

However, it will still do this when you first open cgdb, because apparently gdb prints something prior to reading its init file, and has not yet applied the pagination off setting.

Not ideal, but might help you in the meantime.

**Comment by brasko** [comment] 2021-12-07 03:04
This was supposed to be a feature, not a bug. CGDB now honors the gdb pagination the same way gdb would.

However, when in cgdb, the gdb window is naturally smaller, causing a pagination break when in cgdb but not when using standalone gdb. I understand why this would seem like a new issue.

I would have expected 'set height 0' or 'set pagination 0' to be the workaround, but apparently that's not the case. As @dflogeras  pointed out, gdb still nags you once.

Are you OK with passing -q to gdb to prevent this from happening?

I honestly can't even think of another workaround at the moment. Do you have any ideas? I think it may be a gdb bug.

**Comment by brasko** [comment] 2021-12-07 03:14
https://stackoverflow.com/questions/61471492/cant-disable-pagination-in-gdb

The known solution appears to be to pass -q on startup. Do you agree this is a suitable solution?

**Comment by yurivict** [comment] 2021-12-07 03:15
> The known solution appears to be to pass -q on startup. Do you agree this is a suitable solution?

Yes.

**Comment by brasko** [comment] 2021-12-19 00:46
Should I force cgdb to pass -q to gdb on startup? Or close this issue as is? Thoughts?

**Comment by brasko** [comment] 2021-12-22 01:49
I'm closing this, I believe the reporter is satisfied with the work around.
Someone please reopen and provide a suggestion if they are unsatisfied. Thanks.

**Closed by brasko** 2021-12-22 01:49 UTC
