### ISSUE TITLE
chinese support in ubuntu error

### ISSUE THREAD

**Issue by westrength** [cgdb/cgdb#188] opened 2018-09-19 07:37 UTC
I'm using ubuntu 18.04.1 LTS and cgdb version 0.6.7, found that chinese support in ubuntu error.

![selection_007](https://user-images.githubusercontent.com/17335099/45754052-28ee2700-bc4d-11e8-8c89-f81c36566059.png)

but I use gdb it correct

![selection_009](https://user-images.githubusercontent.com/17335099/45737953-c2074880-bc21-11e8-9e3e-340df31d23fa.png)

What should I do? Please

**Comment by brasko** [comment] 2018-10-02 01:46
Can you please provide a simple main program that I can compile that demonstrates the issue in CGDB?

**Comment by westrength** [comment] 2018-10-02 11:53
Thank you for your reply.
Source code of the issue in CGDB in below accessory.

brasko <notifications@github.com> 于2018年10月2日周二 上午9:46写道：

**Comment by westrength** [comment] 2018-10-03 13:36
Source code of the issue in CGDB in below accessory.
Or see source code at
https://github.com/westrength/solutions-to-CLRS/blob/master/02%E4%BA%8C%E5%8F%89%E6%8E%92%E5%BA%8F%E6%A0%91_BinarySortTree_UTF-8.c
Or see in the picture:
[image: Selection_014.png]

brasko <notifications@github.com> 于2018年10月3日周三 上午9:23写道：

**Comment by westrength** [comment] 2018-10-03 14:57
Below simple source code can reproduces the issue in CGDB.
```
#include <stdio.h>

/* 输出两个数的和 */      

int addSum(int a,int b)
{
    return a+b;
}

int main()
{
    int a,b,sum=0;
    a=2;
    b=5;
    sum = addSum(a,b);
    printf("a+b=%d\n",sum); /* 输出两个数的和 */
    return 0;
}
```
![selection_016](https://user-images.githubusercontent.com/17335099/46419055-99be3480-c75f-11e8-822f-83a67ddbf9dc.png)

**Comment by brasko** [comment] 2018-10-04 12:54
I reproduced the issue in .6.7 and .6.8.
However, I'm glad to report the issue is fixed in .7.0. Upgrade and Enjoy.

**Closed by brasko** 2018-10-04 12:54 UTC

**Comment by westrength** [comment] 2018-10-04 15:00
The issue is not fixed in .7.0.

**Comment by westrength** [comment] 2018-10-23 14:39
I found that how to solve this problem -  [chinese support in ubuntu error #188](https://github.com/cgdb/cgdb/issues/188).
First download the package's source code(suggest cgdb 0.7.0), cd to the directory containing the package's source code.
Then:

    ./configure
    make
    make install
when use cgdb debugged program with Chinese comment ,may be occur messy code.

Solution:
    
    sudo apt-get install libncursesw5
    cd /lib/x86_64-linux-gnu                       # (64 bit)
    $ ls -al libncurses*
    sudo rm -rf libncurses.so.5
    sudo ln -s libncursesw.so.5.9 libncurses.so.5
Then when you reuse cgdb ,get error. Reinstall cgdb .
cd to the directory containing the package's source code.
Then:

    ./configure
    make
    make install
You can normal use cgdb.That's all.
