### ISSUE TITLE
No rule to make target 'fork_util.c', needed by 'fork_util.o'

### ISSUE THREAD

**Issue by step-** [cgdb/cgdb#88] opened 2016-09-16 11:20 UTC
No rule to make target 'fork_util.c', needed by 'fork_util.o'

This happened while compiling commit 375de49 &mdash; which follows the project switch to C++ &mdash; from the previous compilation of commit e25327c &mdash; which precedes C++.

autogen.sh, aclocal, autoconf, etc. didn't establish a clean enough slate. I was finally able to clear the error and compile by doing
```
rm -Ir `find -name .deps`
./autogen.sh
make
```

**Comment by brasko** [comment] 2016-10-12 14:50
Since this doesn't happen with a clean checkout of cgdb, I'm going to close the issue.

If you can reproduce with a clean checkout I'd be happy to fix it.

**Closed by brasko** 2016-10-12 14:50 UTC

**Comment by step-** [comment] 2016-10-17 09:34
OK. I fetched the latest repo and recompiled today, and this issue doesn't occur anymore. Thanks.
