### ISSUE TITLE
Can't see colors in CGDB

### ISSUE THREAD

**Issue by Muffo** [cgdb/cgdb#129] opened 2017-04-05 21:31 UTC
I have just installed the version 0.7.0 and the colors are not displayed when I run cgdb.

In particular, I am referring to both the syntax highlighting and the red marker when a break point is enabled.

Is there any setting I should check in cgdb or in my shell / Putty?

Is there at least a way to display breakpoints with a marker instead of changing the color of the line number?

**Comment by brasko** [comment] 2017-04-06 01:46
That's pretty strange. What's the TERM environment variable set to when you start cgdb?

**Comment by Muffo** [comment] 2017-04-06 01:56
Here are my environment variables:

    TERM=screen
    COLORTERM=1

I have been using `cgdb` for a while on a different machine and colors have always worked OK. This is a fresh installation on a different computer, and I haven't tried any old version yet.

**Comment by brasko** [comment] 2017-04-06 14:21
Can you do 'ldd ./cgdb' and see if it linked against curses or ncurses?

**Comment by Muffo** [comment] 2017-04-06 16:09
Here is the output of the command:

```
$ ldd ./cgdb
        linux-vdso.so.1 =>  (0x00007ffff7ffe000)
        libreadline.so.5 => /lib64/libreadline.so.5 (0x00007ffff7d9b000)
        libncursesw.so.5 => /lib64/libncursesw.so.5 (0x00007ffff7b46000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007ffff7943000)
        libstdc++.so.6 => /usr/intel/pkgs/gcc/4.6.2/lib64/libstdc++.so.6 (0x00007ffff763f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ffff73c5000)
        libgcc_s.so.1 => /usr/intel/pkgs/gcc/4.6.2/lib64/libgcc_s.so.1 (0x00007ffff71b0000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffff6e34000)
        libncurses.so.5 => /lib64/libncurses.so.5 (0x00007ffff6beb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ffff69e7000)
        /lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
```

**Comment by brasko** [comment] 2017-04-06 22:39
If you are building from source, I'll add in some logging that will help explain at what point
cgdb is going wrong. Then we could take it from there. Is that a possibility?

**Comment by Muffo** [comment] 2017-04-07 17:59
That sounds good!

**Comment by BianChengNan** [comment] 2017-07-16 15:20
no color display too. I run cgdb0.7.0(offical release version, not built from source,I just can't make successfully!) on RHEL5.9, I'm fresh to linux and a new user of cgdb(quit nice!), below is my ldd result

ldd ./cgdb 
	linux-vdso.so.1 =>  (0x00007fff61bfd000)
	libreadline.so.5 => /usr/lib64/libreadline.so.5 (0x00000039afe00000)
	libncursesw.so.5 => /usr/lib64/libncursesw.so.5 (0x00000039aee00000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00000039bb400000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00000039c0000000)
	libm.so.6 => /lib64/libm.so.6 (0x00000039ae200000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00000039bc000000)
	libc.so.6 => /lib64/libc.so.6 (0x00000039ade00000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00000039ae600000)
	/lib64/ld-linux-x86-64.so.2 (0x00000039ada00000)

will cgdb_gdb_io_log1.txt help?

thanks for the great tool and any help is appreciated.

**Comment by brasko** [comment] 2017-07-18 11:46
I'm not sure why this is happening actually. I'll add some logging into cgdb this week.

Perhaps you could build from source to prepare for that? I'm sure we can figure it out.

**Comment by 10110111** [comment] 2017-07-23 16:05
This used to work with `TERM=xterm` in some previous versions. Now you have to set `TERM=xterm-256color` to get colors. I've done `git bisect`, here's the result:
```
7b0bdbd7aabf069fc726992fee4d8ab9f7c89bbc is the first bad commit
commit 7b0bdbd7aabf069fc726992fee4d8ab9f7c89bbc
Author: Michael Sartain <mikesart@gmail.com>
Date:   Sat May 21 09:27:36 2016 -0700

    Add ansi_color check and support
    Kill several mallocs / reallocs in parse, use wclrtoeol
    
    Signed-off-by: Michael Sartain <mikesart@gmail.com>
    Signed-off-by: Bob Rossi <bob@brasko.net>

:040000 040000 ab6a72c298313e165eccf6889f7530b64694b7d3 739c92a667a93db9f9e5046a1440a68c87e4764e M      cgdb
:040000 040000 49bf6a19cc6651126e18ef625118a80c7dbfdc74 a802beff7cec7e20d39c254d92fcddf74b0b7e62 M      lib
```
Anyway, I think setting `TERM` to `xterm-256color` is good enough a solution for me, since it also lets Vim use 256-color palette instead of the default 16 colors, without fiddling with `t_Co` option. I guess this will be useful for some other console apps too.

**Comment by brasko** [comment] 2017-07-24 22:42
Wow, thanks so much for taking the time to do this.

I'll look at this tonight (I hope) and add some logging in at certain points that will perhaps aid me in where it is going wrong now.

Thanks!

**Comment by brasko** [comment] 2017-07-25 23:15
I've pushed some changes to master. Could you rebuild and let me know what your cgdb log says?

This file should look something like,
~/.cgdb/logs/cgdb_log1.txt

2017-07-25 16:41:44 highlight_groups.cpp:526() INFO:Color support: Enabled
2017-07-25 16:41:44 highlight_groups.cpp:528() INFO:ANSI color support: Enabled
2017-07-25 16:41:44 highlight_groups.cpp:530() INFO:Number colors: 8
2017-07-25 16:41:44 highlight_groups.cpp:531() INFO:Number color pairs: 64

I'm assuming yours is different and perhaps this will help us out.

**Comment by 10110111** [comment] 2017-07-26 05:27
Here's mine:
```
2017-07-26 08:24:01 highlight_groups.cpp:526() INFO:Color support: Enabled

2017-07-26 08:24:01 highlight_groups.cpp:528() INFO:ANSI color support: Enabled

2017-07-26 08:24:01 highlight_groups.cpp:530() INFO:Number colors: 8

2017-07-26 08:24:01 highlight_groups.cpp:531() INFO:Number color pairs: 64

2017-07-26 08:24:06 tgdb.cpp:599() ERROR:waitpid error

2017-07-26 08:24:06 tgdb.cpp:371() INFO:Closing logfile.
```

**Comment by brasko** [comment] 2017-07-26 10:33
OK. That was unexpected. I'll produce more relevant logging information today.
Hopefully we can narrow this down. 

I am correct in assuming that the cgdb display of the source code does not appear syntax highlighted, correct?

**Comment by 10110111** [comment] 2017-07-26 10:35
Yeah, neither source, nor assembly, not even CGDB logo. Syntax highlighting only boldifies some tokens, without color.

**Comment by brasko** [comment] 2017-07-26 13:47
I just want to double check that the logging you shared was when you had TERM=xterm and colors did not work. Correct?

**Comment by 10110111** [comment] 2017-07-26 13:54
Yes, for `xterm-256color` I have values 256 and 32767.

**Comment by mikesart** [comment] 2017-07-26 16:20
Can I ask what terminal emulator (and version) you're using? With GNOME Terminal v3.22.2 and xfce4-terminal v0.8.5.1 cgdb has color with TERM set to screen and xterm for me.

Could you also do a "infocmp -L xterm" and stick a pointer to the results for that somewhere?

Thanks!

**Comment by 10110111** [comment] 2017-07-26 19:35
> Can I ask what terminal emulator (and version) you're using?

I tested with the following terminals on a system with ncurses-5.6:
* Konsole: 2.14.2
* Yakuake: 2.9.9 (with the same Konsolepart)
* GNOME gnome-terminal 2.18.1
* XTerm(301)
* Linux VT (intel KMS) 3.12.18

Output from `infocmp -L xterm`: https://pastebin.mozilla.org/9028047 .

**Comment by brasko** [comment] 2017-07-26 22:10
I've pushed 2 more commits. We used to ignore the return value of init_pair and
a few other ncurses functions. Now if they fail, we log them. Can you let me know
if you get any new error messages in the logs?

**Comment by mikesart** [comment] 2017-07-26 22:20
This is from the ncurses 6.0 announcement:

> https://www.gnu.org/software/ncurses/
> modify init_pair to accept -1's for color value after assume_default_colors has been called.

Guessing this is probably the issue. Hopefully your init_pair() check should verify init_pair is failing with ncurses-5.6.

**Comment by mikesart** [comment] 2017-07-26 22:37
Ok, that was a pointer to ncurses 6, not ncurses 5, version 6.

However going through the ncurses changelog, I found this entry for ncurses 5, version 5.9:

ncurses (5.9+20130119-1) experimental; urgency=low
  * New upstream patchlevel.
    - Modify init_pair() to accept -1's for color value after
      assume_default_colors() has been called (Closes: #337095).

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=337095

**Comment by brasko** [comment] 2017-07-27 00:53
Thanks Michael. I just built ncurses 5.6 (and cgdb) with the following options
  ../ncurses-5.6/configure --prefix=$PWD/../prefix --without-cxx --without-cxx-binding --without-ada  --with-shared --enable-widec

Now I can reproduce the issue with seeing no colors. We guessed right,
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=64 f=7 b=7
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=65 f=0 b=-1
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=66 f=1 b=-1
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=67 f=2 b=-1
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=68 f=3 b=-1
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=69 f=4 b=-1
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=70 f=5 b=-1
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=71 f=6 b=-1
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=72 f=7 b=-1
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=73 f=-1 b=0
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=74 f=-1 b=1
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=75 f=-1 b=2
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=76 f=-1 b=3
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=77 f=-1 b=4
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=78 f=-1 b=5
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=79 f=-1 b=6
2017-07-26 20:47:46 sys_win.cpp:256() ERROR:init_pair failed pair=80 f=-1 b=7

At least this gives us direction to start thinking about a solution.

**Comment by brasko** [comment] 2017-07-27 01:33
I'm wondering if we can't try to do an init_pair on 64, and if it fails, fall back to non ansi mode.
That way, users would still have basic color support, but no ansi color support.
Does that make sense?

**Comment by mikesart** [comment] 2017-07-27 19:08
Sure. Not sure how feasible it is, but it would be nice to somehow notify the user as well so they're not wondering why they're not getting color. Thanks Bob.

**Comment by brasko** [comment] 2017-07-28 22:53
Should be fixed, let me know otherwise.

Ansi color will be disabled, but you will have color support.

**Closed by brasko** 2017-07-28 22:53 UTC

**Comment by 10110111** [comment] 2017-07-29 05:11
Confirming fixed.

**Comment by 10110111** [comment] 2017-07-29 05:15
Hmm, one of the logos appears broken, not sure if it's related to this problem:

**Comment by mikesart** [comment] 2017-07-29 19:30
Can you open a new bug for this please? Put this in the comment:

You can reproduce this by putting "set nocolor" in the cgdbrc file, and typing ":logo" until one of the colored logos appears. I think the fix is for the logo_display() function to limit itself to one of the first three logos if color is disabled.

Thanks.

**Comment by Muffo** [comment] 2017-08-02 17:57
I have just tested the fix on my server.

When I start cgdb I get the following message:

```
                                                                                    ^[[0;1;35;95m  ^[[0m       ^[[0;1;36;96m_^[[0;1;34;94m\|^[[0;1;35;95m/_^[[0m
                                                                                             ^[[0;1;36;96m(^[[0;1;34;94mo^[[0m ^[[0;1;35;95mo)^[[0m
                                                                                     ^[[0;1;35;95m+^[[0;1;31;91m--^[[0;1;33;93m--^[[0;1;32;92moO^[[0;1;36;96mO-^[[0;1;34;94m{_^[[0;1;35;95m}-
^[[0;1;31;91mOO^[[0;1;33;93mo-^[[0;1;32;92m-+^[[0m                                   ^[[0;1;35;95m|^[[0m                 ^[[0;1;32;92m|^[[0m
                                                                                     ^[[0;1;35;95m|^[[0m      ^[[0;1;36;96mcg^[[0;1;34;94mdb^[[0m       ^[[0;1;32;92m|^[[0m
                                                                                     ^[[0;1;35;95m|^[[0m                 ^[[0;1;32;92m|^[[0m
                                                                                     ^[[0;1;35;95m+^[[0;1;31;91m--^[[0;1;33;93m--^[[0;1;32;92m--^[[0;1;36;96m--^[[0;1;34;94m--^[[0;1;35;95m--
^[[0;1;31;91m--^[[0;1;33;93m--^[[0;1;32;92m*/^[[0m
                                                                                      a curses debugger
                                                                                      version 20170802

                                                                           type  q<Enter>            to exit
                                                                           type  help<Enter>         for GDB help
                                                                           type  <ESC>:help<Enter>   for CGDB help
```

However, if I set `$TERM` to `screen-256color` I am able to see the colors again :)
Thanks for the fix! 👍

**Comment by 10110111** [comment] 2017-08-02 18:31
@Muffo I've already reported this as #139.
