### ISSUE TITLE
keyboard input gets ignored when you open the file dialog while the program is running

### ISSUE THREAD

**Issue by rinzlxr** [cgdb/cgdb#243] opened 2020-11-29 21:35 UTC
### Environment:
OS: Arch Linux
cgdb version: CGDB 20201129

### Steps to reproduce
- run `cgdb ./program`
- in the gdb console run  the program
- while the program is running enable the source window and press `o`

### Result:
cgdb doesn't respond to any key except Ctrl-C which means you can pause the running program but can use cgdb anymore

To alleviate the issue one can pause the program before trying to access the File dialog

**Comment by brasko** [comment] 2021-03-01 02:45
Is this reproducible? I've never seen this before.

**Comment by marehr** [comment] 2021-03-01 12:34
I stopped using cgdb, because of this. So all I can say is that it was an issue. I have arch linux too.

Plus https://github.com/cgdb/cgdb/issues/239.

**Comment by brasko** [comment] 2021-03-13 03:56
I'm closing this as not reproducible.  If someone can reproduce, we'll reopen.

**Closed by brasko** 2021-03-13 03:56 UTC
