### ISSUE TITLE
it output messly when enter 'next<CR>'

### ISSUE THREAD

**Issue by PeterlitsZo** [cgdb/cgdb#222] opened 2020-03-10 06:05 UTC
I download the package cgdb-0.7.1.tar.gz form https://cgdb.github.io/, and then run command like this:
``` shell
$ <path-to-cgdb-package>/configure --prefix=$PWD/../cgdb #cgdb is a new dir
$ make
$ sudo make install
$ <path-to-cgdb-bin>/cgdb a.out
```

after that, it show like this:
`peterlits.com/!00fc9c`
`peterlits.com/!526164`

thanks a lot.
p.s. if these pics can't be opened, please tell me and I'll try another way

**Comment by PeterlitsZo** [comment] 2020-03-10 07:10
when i delete the files named ~/.cgdb and ~/.gdbinit, it output normally, but it still can't quit when i am in the command 'scanf'.
the only way to quit it is use <Esc>:q<CR>
but when i use gdb it can just run when i enter the <CR>.

thanks a lot

**Comment by iandinwoodie** [comment] 2020-03-10 10:33
@PeterlitsZo , please embed your images or post them to a trusted hosting platform (e.g., imgur, photobucket, flickr).

**Comment by iandinwoodie** [comment] 2020-03-10 10:36
>  but it still can't quit when i am in the command 'scanf'

cgdb does not support reading from cgdb from either the gdb or cgdb windows. To do so, you need to run the process in one terminal and then use cgdb to attach to the process in another terminal using the `-p <pid` flag.

**Comment by PeterlitsZo** [comment] 2020-03-10 10:42
thanks for your reply, and there are those pics:
https://imgur.com/aHekzIt
https://imgur.com/JWdD4D0

**Comment by PeterlitsZo** [comment] 2020-03-10 10:44
but after i remove some file, it didn't looked in a mess like this...
`_`

**Comment by PeterlitsZo** [comment] 2020-03-10 11:13
> > but it still can't quit when i am in the command 'scanf'
> 
> cgdb does not support reading from cgdb from either the gdb or cgdb windows. To do so, you need to run the process in one terminal and then use cgdb to attach to the process in another terminal using the `-p <pid` flag.

i am so sorry that i do not understand it very well. in my point of view, the sign `<` should be in the front of a file's name, and that's why it tell me `zsh: no such file or directory: 14528`

**Comment by brasko** [comment] 2020-04-05 00:01
Duplicate of #209

**Closed** 2020-04-05 00:01 UTC
