### ISSUE TITLE
Weird output in gdb console

### ISSUE THREAD

**Issue by honggyukim** [cgdb/cgdb#113] opened 2017-02-03 23:09 UTC
Hi, I've found some problems from the recent changes.
You can see the problem from the following output:
```
(gdb) b main
(gdb) (gdb) r
Starting program: /home/honggyu/a.out

Breakpoint 1, main () at /home/honggyu/hello.c:5
(gdb) s
_IO_puts (str=0x400674 "Hello World!") at ioputs.c:34
34      ioputs.c: No such file or directory.
(gdb) (gdb)
36      in ioputs.c
(gdb) (gdb)
strlen () at ../sysdeps/x86_64/strlen.S:66
66      ../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) (gdb)
67      in ../sysdeps/x86_64/strlen.S
(gdb) (gdb) (gdb)
```
I've tested it and found that the commit 0db5a3a is the problem.
So please have a look at it.

**Comment by mikesart** [comment] 2017-02-04 00:00
Hi honggyukim. What version of gdb are you using and what platform + version of that?

**Comment by honggyukim** [comment] 2017-02-04 01:04
Hi mikesart,

I use Ubuntu 14.04.5 LTS and gdb version is as follows:
```
$ gdb --version
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
```

**Comment by mikesart** [comment] 2017-02-04 01:14
I'll try to run that version in a docker instance and reproduce this in the next couple days. Just for sanity, could you verify that the problem still exists when you disable gdb init files. Something like this?
```
cgdb --nx
```
Thanks!

**Comment by honggyukim** [comment] 2017-02-04 01:29
The problem is still there with `cgdb --nx`.
Please take a look at it. Thanks!

**Comment by mikesart** [comment] 2017-02-04 05:43
I'm not able to reproduce this with Ubuntu 14.04.5 LTS and gdb 7.7.1. Can you give me the output of "uname -a" and what is your TERM set to?

```
Reading symbols from blah/blah...done.
(gdb) b main
Breakpoint 1 at 0x4005cc: file blah.c, line 28.
(gdb) r
Starting program: /home/blah/blah

Breakpoint 1, main (argc=1, argv=0x7fffffffe7e8) at blah.c:28
(gdb) n
(gdb) n
(gdb)
Color test app...

(gdb)
```

**Comment by brasko** [comment] 2017-02-07 02:11
Yes, I'm pretty sure this is my fault. I've got to get to the bottom of this before the release.
This happens when tgdb.cpp:tgdb_process returns is_finished true when it shouldn't.

**Comment by honggyukim** [comment] 2017-02-07 02:42
@mikesart Here is the info you requested.
```
$ uname -a
Linux ubuntu 3.19.0-78-generic #86~14.04.1 SMP Wed Feb 1 11:11:01 KST 2017 x86_64 x86_64 x86_64 GNU/Linux
`
$ echo $TERM
xterm
``

**Comment by brasko** [comment] 2017-02-10 04:27
When I rewrote the annotations code, I failed to take a few cases into account that were previously handled. Ctrl-c from the terminal was one of those issues, which is now fixed hopefully.
Another issue I appeared to break is the one you are seeing. I'll tackle that next.

**Comment by brasko** [comment] 2017-03-02 01:57
Should be good now, let me know if this is still a problem.

Sorry it took so long to fix!

**Closed** 2017-03-02 01:57 UTC
