### ISSUE TITLE
CGDB freezes when pressing "o" to open the file dialog

### ISSUE THREAD

**Issue by alefa** [cgdb/cgdb#135] opened 2017-06-04 10:11 UTC
As the title says, CGDB always freezes for me when I press "o" in CGDB mode to access the file dialog window. The CPU usage goes up to 100%, and I have to close the terminal window to kill CGDB.
This bug is reproducible with a simple "Hello world" C++ program compiled with the -g switch. I'm using CGDB 0.7.0 compiled from source on Debian Stretch. Please let me know what other information I can provide to help find the cause of this bug.

**Comment by brasko** [comment] 2017-06-07 12:46
I've seen this before, but it's been a while.

Perhaps send me the log files in ~/.cgdb/logs
and your .cgdbrc file?

**Comment by alefa** [comment] 2017-06-08 07:23
Ok, my cgdbrc file contains only a single line:

    set cgdbmodekey=<PageUp>

Here's the log of a session where I started CGDB as `cgdb ./hello`, switched to CGDB mode and pressed "o": [cgdb_gdb_io_log1.txt](https://github.com/cgdb/cgdb/files/1060189/cgdb_gdb_io_log1.txt)
The second log file (cgdb_log1.txt) was empty.

**Comment by brasko** [comment] 2017-06-22 18:16
I've reproduced this I believe.

I'll try to have a fix shortly.

Thanks!
Bob Rossi

**Comment by brasko** [comment] 2017-07-07 01:53
Just an update, I was able to write a test case in gdbwire (which cgdb uses) which reproduces the slow down.

Basically, the number of files returned from gdb is large, and gdbwire inserts them into a linked list.

I'll have to improve the insertion algorithm. That may fix the entire issue, or perhaps there will be similar
issues with cgdb once this is fixed. Should have something soon.

**Comment by alefa** [comment] 2017-07-07 06:27
Excellent! Looking forward to testing your version with the improved 
insertion algorithm.

**Comment by brasko** [comment] 2017-07-11 11:43
Should be all set now. Let me know!

**Comment by alefa** [comment] 2017-07-12 08:08
Just tested the newest version from Git. Unfortunately, it still freezes for me. Here's the log of my session: 
[cgdb_gdb_io_log1.txt](https://github.com/cgdb/cgdb/files/1141277/cgdb_gdb_io_log1.txt)

**Comment by brasko** [comment] 2017-07-13 12:55
Wow. I didn't expect that. So there is yet another issue in the same area. Reopening case.

**Comment by brasko** [comment] 2017-07-18 11:45
I'm going to try to take another stab at this. To bad I fixed the wrong bug last time. :)

Is this reproducible every time for you? 

If so, is it possible you could get in the debugger and let me know what file/line it's stuck in?

**Comment by brasko** [comment] 2017-07-25 23:14
I just noticed you have the + symbol in your log file, for instance,
2017-07-12 10:00:57 io.cpp:136() DEBUG:+(\r)(\n)(\032)(\032)pre-prompt(\r)(\n)(g
I don't have that in my output.

Are you connecting with gdbserver or anything like that? I'm not sure if this is related.

Do you know how to debug cgdb and tell me what line it's on when it is hanging?

**Comment by alefa** [comment] 2017-07-26 18:42
Sorry I didn't get back to you sooner. I really appreciate you trying to 
solve this issue. For me the bug is reproducible every time. I am not 
connecting to gdbserver, I just execute something like "cgdb 
./myprogram", with the program compiled with the -g flag. I don't know 
how to debug cgdb (I've only just started to learn C++) but if you give 
me instructions I will follow them and tell you where it's hanging.

**Comment by brasko** [comment] 2017-10-27 02:06
I can't reproduce the + symbol in the gdb output. That's the problem for sure.

If you can help me reproduce this, I'll fix this issue for you. Otherwise I'm closing the issue.

The partial good news is, I might be moving to all MI soon. In that case, I think this issue
would be resolved as I think this is related to the A2 parsing code.

**Comment by wangjiaming0909** [comment] 2020-04-09 11:13
My cgdb freezes when pressing 'o' too, but only when gdb is in continue state, and it appears every time, my cgdb is build from [8c2f3a2a](https://github.com/cgdb/cgdb/commit/8c2f3a2a632d63366eef419fabf3e8245d9b7a45)

**Comment by oncer** [comment] 2021-05-14 09:24
cgdb version 20200728 freezes for me, when I press "o".
To reproduce, I start it with cgdb <executable>, then I press ESC and hit "o".
[cgdb_gdb_io_log1.txt](https://github.com/cgdb/cgdb/files/6477848/cgdb_gdb_io_log1.txt)

**Comment by brasko** [comment] 2021-05-17 01:36
Please try with git master and let me know. Thanks.

**Comment by oncer** [comment] 2021-05-27 11:31
@brasko it does not freeze with git master 20210527, works as expected.

**Comment by user1095108** [comment] 2021-10-02 10:49
freezes here, 100% CPU usage as before, latest version from master.

**Comment by brasko** [comment] 2021-10-04 01:47
OK. I'd really like to fix this before the next release, which I'm hopeful could be in the next 4-6 weeks.

Any chance you can get me the back trace when it's frozen, and the log files in ~/.cgdb/logs/ and possibly a reproducer?

**Comment by user1095108** [comment] 2021-10-04 04:19
This is a cryptic bug, that has been popping in and out over the years. I associate the latest "pop" with my upgrade to `gdb-11.1` on arch linux, but I could be wrong. I tried a freshly cloned version again and the bug is still there.
```
#0  0x00007ffff7a8c197 in select () from /usr/lib/libc.so.6
#1  0x000055555555d3df in main_loop () at cgdb.cpp:848
#2  main (argc=<optimized out>, argv=<optimized out>) at cgdb.cpp:1225
```
Otherwise, I am using:
Linux e5-2620v2 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64 GNU/Linux

reproducing might be as easy as installing the latest vanilla arch linux.
[](url)
[cgdb_gdb_console_io_log1.txt](https://github.com/cgdb/cgdb/files/7275417/cgdb_gdb_console_io_log1.txt)
[cgdb_gdb_io_log1.txt](https://github.com/cgdb/cgdb/files/7275418/cgdb_gdb_io_log1.txt)
[cgdb_gdb_mi_io_log1.txt](https://github.com/cgdb/cgdb/files/7275419/cgdb_gdb_mi_io_log1.txt)
[cgdb_log1.txt](https://github.com/cgdb/cgdb/files/7275420/cgdb_log1.txt)

**Comment by brasko** [comment] 2021-10-09 02:28
I took the time and I reproduced this. Thanks for sending in the log files, it helped me track this down! Now let me see if I can fix it.

**Comment by brasko** [comment] 2021-10-09 15:38
Excellent! Enjoy. If anyone still has the issue, then we can reopen the case. Otherwise it's closed!

**Closed by brasko** 2021-10-09 15:38 UTC

**Comment by ensisoft** [comment] 2025-02-14 20:22
Hey, holy shit back in the day I used cgdb since it's the best frontend there is for gdb and then this bug turned into a showstopper. Randomly today I decided to have a look about this hang and turns out it's fixed!

Awesome. Thanks for this!
