### ISSUE TITLE
ylwrap fails with rustlexer.lpp

### ISSUE THREAD

**Issue by 10110111** [cgdb/cgdb#137] opened 2017-07-13 09:47 UTC
On my system with automake-1.12, `ylwrap` command fails due to mismatch between what it expects as `flex`'s output file (`lex.yy.c`) and what it actually has (`rustlexer.cpp`). I fixed it locally with this:

```
diff --git a/lib/tokenizer/rustlexer.lpp b/lib/tokenizer/rustlexer.lpp
index 544eb73..ea3866f 100644
--- a/lib/tokenizer/rustlexer.lpp
+++ b/lib/tokenizer/rustlexer.lpp
@@ -1,5 +1,5 @@
 %option prefix="rust_"
-%option outfile="rustlexer.cpp"
+%option outfile="lex.yy.c"
 
 B       [01_]
 O       [0-7_]
```

But I'm not sure if it's the correct fix — maybe I'm just using too old/new automake or whatever. In any case, all the other `*.lpp` files have `outfile="lex.yy.c"` option, only `rustlexer.lpp` has a different outfile.

**Comment by BianChengNan** [comment] 2017-07-16 15:33
similar problem, I try to build cgdb use the latest sourse on github, but I failed. rustlexer.cpp should be generated by rustlexer.lpp automatically? I guess so, but it was not generated. I don't make it clear how to configure.
by the way, I can build cgdb successfully using the stable release tar.gz from offical release site.https://cgdb.github.io/
but it can't show color. 

is the tool(build needed) version not correct? which version should be used?

I google a lot, no help. waitting for reply... thanks in advance.

**Comment by brasko** [comment] 2017-07-18 11:42
Thanks for the fix! This was reported before but I couldn't reproduce it. Fixed in master.

**Closed by brasko** 2017-07-18 11:42 UTC
