### ISSUE TITLE
cgdb stucked

### ISSUE THREAD

**Issue by tanghammer** [cgdb/cgdb#183] opened 2018-08-08 03:18 UTC
when i  use 'commands' command to set  breakpoint command lists, press tab ,cgdb will stucked.tab is auto complement.

**Comment by idinwoodie** [comment] 2018-08-25 17:10
@tanghammer are you still experiencing this issue? If you are experiencing the issue, can you provide the following:
1. Your operating system
2. Your cgdb version
3. Your gdb version

**Comment by brasko** [comment] 2018-09-08 00:51
This is a duplicate of issue #67. Closing this one.

**Closed by brasko** 2018-09-08 00:51 UTC
