### ISSUE TITLE
The gdb process often stays when cgdb exits

### ISSUE THREAD

**Issue by yurivict** [cgdb/cgdb#291] opened 2021-11-04 19:57 UTC
I start cgdb as a child from another program. When the invoking program dies cgdb always dies but gdb often stays.

After gdb and the calling invoking process exit gdb has the ```init``` process as parent.

cgdb should always ensure that gdb is killed when it exits.

Version: 0.7.1
OS: FreeBSD 13

**Comment by brasko** [comment] 2021-11-19 02:55
Do you have any thoughts on the typical way to ensure that gdb is killed whenever cgdb is killed?

**Comment by yurivict** [comment] 2021-11-19 03:45
One way is to add handle for every signal that causes process termination and kill gdb from it.

**Comment by brasko** [comment] 2021-12-19 00:47
OK, I'll investigate this more.

**Comment by brasko** [comment] 2021-12-22 02:01
I'd like to fix this before releasing. Is there any chance you can provide steps to reproduce?

If I start cgdb, and then kill it, both cgdb and gdb exit.
Do you have steps where cgdb exits but gdb remains running?

**Comment by brasko** [comment] 2022-01-11 03:13
I'll be preparing a release shortly.
@yurivict Any chance you have better duplication steps? If not, I'm afraid I'll release without this fix.

**Comment by yurivict** [comment] 2022-01-12 21:27
Sorry, I can't reproduce this at the moment.

I will add steps once I am able to reproduce.

Please don't hold release for this.

**Comment by amosbird** [comment] 2022-05-29 05:07
I also noticed this issue after the Major CGDB update 0a16115c92c043626ff702ad67226ab6f2260715

Before that, even `pkill -9 cgdb` will not leave gdb process hanging.

**Comment by brasko** [comment] 2024-05-18 12:36
Is this still an issue? I can't reproduce it.
If i start cgdb, then pkill -9 cgdb, i don't see any open gdb process.

**Comment by yurivict** [comment] 2024-05-18 14:28
I don't use cgdb much now to tell.

**Comment by brasko** [comment] 2024-05-18 18:24
@amosbird Any chance you still see this issue?

**Comment by amosbird** [comment] 2024-05-18 18:55
I can still reproduce it. (I'm on commit aafd7206a5d61c72536948a138e9c1ecf30b7386)

**Comment by brasko** [comment] 2024-05-19 12:09
@amosbird Thanks for the info!

Does pkill -9 cgdb leave cgdb gone but gdb still running in the background?
If not, can you post the reproducer?
I'll try to fix this before the next release.

**Comment by amosbird** [comment] 2024-05-19 13:15
> Does pkill -9 cgdb leave cgdb gone but gdb still running in the background?

Yes.

> If not, can you post the reproducer? I'll try to fix this before the next release.

I'll investigate. Thanks!

**Comment by amosbird** [comment] 2024-05-19 13:49
I failed to build a minimal reproducible binary for this. But I do find a way to reproduce it via clickhouse server.

You can try the following:

```
wget https://github.com/ClickHouse/ClickHouse/releases/download/v24.4.1.2088-stable/clickhouse-common-static-24.4.1.2088-amd64.tgz

tar xzf clickhouse-common-static-24.4.1.2088-amd64.tgz

cd clickhouse-common-static-24.4.1.2088

cgdb usr/bin/clickhouse

run server

continue
``` 

Don't worry. It will only generate files under folder `clickhouse-common-static-24.4.1.2088`. It will occupy some tcp ports by default (8123, 9000, 9004).

Make sure clickhouse server is up and running ( you can check it by doing  `curl 127.0.0.1:8123` )

Now `kill -9 <cgdb_pid>`. gdb process will still be alive.

**Comment by brasko** [comment] 2024-05-23 02:33
@amosbird Thank you so much for the reproducer. It took a little while, but i figured out the issue, both because of your reproducer, and because you told me what version you started to see the issue in.

Please let me know if you see the issue resolved in master. Thanks!

**Comment by amosbird** [comment] 2024-05-23 03:14
@brasko 471c33a works. Thank you!

**Closed** 2024-05-24 00:24 UTC
