### ISSUE TITLE
Strange breakpoints show on file

### ISSUE THREAD

**Issue by vlachoudis** [cgdb/cgdb#293] opened 2021-11-16 15:10 UTC
Some times after debugging a program when I scroll in the file I get breakpoints highlighted that are fictitious (I didn't set them)
![image](https://user-images.githubusercontent.com/3834594/142011170-7ec8d047-d76a-495b-bd2e-949ebb7d2520.png)

**Comment by brasko** [comment] 2021-11-19 02:54
Are there any specific steps you are aware of to reproduce this problem?

**Comment by vlachoudis** [comment] 2021-11-19 07:39
It happens randomly. Typically I leave the debugger open and recompile the program and restart it in the debugger with the same breakpoints, and after some time it happens that it shows fictions break points

**Comment by vlachoudis** [comment] 2021-11-19 07:40
The source code is changing in between compiles, and cgdb correctly is reloading the source code and I think is when it happens

**Comment by brasko** [comment] 2021-11-19 11:41
Thanks! Very helpful info. I’ll see what i can do!

**Comment by brasko** [comment] 2021-12-19 00:46
Is there any chance you have simple steps to reproduce this like in case #298 ?

I wasn't able to reproduce for some reason.

**Comment by brasko** [comment] 2021-12-22 01:57
I wonder if your situation is that you have changed the source files, but have not yet recompiled.
In this scenario, cgdb will show you the new file, and gdb will be telling you about the old source file breakpoint positions.

If you then recompile your code and run again in gdb, the breakpoints in gdb and the source code in cgdb should be synced.
Can you confirm you are hitting the error reported due to the fact that you changed the code but did not yet recompile and run in gdb? If that's not the case, there is still a bug I can not reproduce. Thanks!

**Comment by brasko** [comment] 2022-01-11 03:12
I'm closing this as I believe it was most likely do to user error.
However, please reopen this if you feel it was closed in error.
I will however need some better duplication steps.

**Comment by meator** [comment] 2022-02-06 14:31
Hello. I am able to reproduce this issue (although it happens only sometimes).
![image](https://user-images.githubusercontent.com/67633081/152684206-63115a0b-66ae-4072-b4a7-8f815cd5a276.png)

# How to reproduce
1. Download my unfinished locale parser: [main.txt](https://github.com/cgdb/cgdb/files/8010354/main.txt)
2. Rename it to `main.c`
3. Create this `Makefile` in the same directory as the `main.c` file:
    ```Makefile
    main: main.c
    	gcc -O0 -ggdb main.c -o main
    ```
4. Build `main` using `make`
5. Run cgdb on it
6. Break on `main()`
7. Run it and step into some random part of my code (for example to line 49 with `nnsnn`)
8. While cgdb is waiting for next instructions, edit the `main.c` file and add some superfluous `int` members to the `struct lang` (I have added nine of them)
9. Switch back to cgdb and type `make` in the gdb interface
10. Type `run`
11. Type `y` to confirm starting the program from the beginning, even when it is still running.

It is pretty random, but this almost always creates ghost breakpoints in my cgdb. I hope this will help you to diagnose the issue.

**Comment by brasko** [comment] 2022-02-08 03:34
Thanks for the steps to reproduce this. It didn't work for me first try, but i'm going to try again a few times.
What version of GDB are you using? I assume you are using master for CGDB?

**Comment by meator** [comment] 2022-02-08 15:24
I am using 0.8.0, but I was able to reproduce it by compiling cgdb with the latest commit.

I have simplified the instruction for reproducing the issue.

**Comment by brasko** [comment] 2022-02-09 11:49
Thanks for taking the time to do this. I was finally able to reproduce the issue! I'm a bit busy at the moment, I'll provide a fix in about two weeks I hope. I'll do another minor release as well.

**Comment by brasko** [comment] 2022-02-18 03:31
Should be fixed. Please let me know otherwise and I'll reopen. Thanks!

**Closed by brasko** 2022-02-18 03:31 UTC
